SELECT * FROM TB_DEPARTMENT;
SELECT * FROM TB_CLASS;
SELECT * FROM TB_PROFESSOR;
SELECT * FROM TB_CLASS_PROFESSOR;
SELECT * FROM TB_STUDENT;
SELECT * FROM TB_GRADE;

-----------------------------------------------------------------
-- SELECT (OPTION)


-- 1. 영어영문 학번, 이름, 입학년도
SELECT STUDENT_NO 학번, STUDENT_NAME 이름, ENTRANCE_DATE 입학년도
FROM TB_STUDENT S
JOIN TB_DEPARTMENT D ON (S.DEPARTMENT_NO = D.DEPARTMENT_NO)
WHERE D.DEPARTMENT_NO = '002'
ORDER BY ENTRANCE_DATE ASC;

-- 2. 세글자가 아닌 교수님 이름, 주민번호
SELECT PROFESSOR_NAME, PROFESSOR_SSN 
FROM TB_PROFESSOR
WHERE LENGTH(PROFESSOR_NAME ) != 3;


-- 3. 교수님 이름, 나이
SELECT PROFESSOR_NAME 교수이름, 
ABS(FLOOR(MONTHS_BETWEEN(SYSDATE, TO_DATE(SUBSTR(PROFESSOR_SSN,1,6), 'RRMMDD')) / 12)) "나이"
FROM TB_PROFESSOR
WHERE DECODE(SUBSTR(PROFESSOR_SSN,8,1), '1', '남', '2', '여') = '남'
ORDER BY "나이" ;

-- 나이 구하기
SELECT ABS(FLOOR(MONTHS_BETWEEN(SYSDATE, TO_DATE(SUBSTR(PROFESSOR_SSN,1,6), 'RRMMDD')) / 12)) "나이"
FROM TB_PROFESSOR;

-- 4. 









