SELECT * FROM TB_DEPARTMENT;
SELECT * FROM TB_CLASS;
SELECT * FROM TB_PROFESSOR;
SELECT * FROM TB_CLASS_PROFESSOR;
SELECT * FROM TB_STUDENT;
SELECT * FROM TB_GRADE;

-----------------------------------------------------------------
-- SELECT - BASIC

-- 1. 학과, 이름 계열
SELECT DEPARTMENT_NAME "학과 명", CATEGORY 계열 
FROM TB_DEPARTMENT;


-- 2. 학과의 학과 정원
SELECT DEPARTMENT_NAME "학과 명" ,CAPACITY "학과별 정원"
FROM TB_DEPARTMENT;


-- 3. 국어국문학과 여학생 휴학중  
SELECT STUDENT_NAME
FROM TB_STUDENT
JOIN TB_DEPARTMENT USING(DEPARTMENT_NO)
WHERE DEPARTMENT_NAME = '국어국문학과'
AND DECODE(SUBSTR(STUDENT_SSN,8,1), '1', '남', '2', '여') = '여'
AND ABSENCE_YN = 'Y';


-- 4. 도서관 대출 장기 연체자
SELECT STUDENT_NAME
FROM TB_STUDENT
WHERE STUDENT_NO IN ('A513079', 'A513090', 'A513091', 'A513110', 'A513119')
ORDER BY STUDENT_NO DESC;


-- 5. 입학정원 20명 이상 30명 이하 학과, 계열
SELECT DEPARTMENT_NAME, CATEGORY 
FROM TB_DEPARTMENT
WHERE CAPACITY >= 20 AND CAPACITY <= 30;


-- 6. 대학교 총장
SELECT PROFESSOR_NAME
FROM TB_PROFESSOR
WHERE DEPARTMENT_NO IS NULL;


-- 7. 전산상 착오로 학과 지정 X 학생
SELECT * 
FROM TB_STUDENT
WHERE DEPARTMENT_NO IS NULL;


-- 8. 선수과목 여부
SELECT CLASS_NO 
FROM TB_CLASS
WHERE PREATTENDING_CLASS_NO IS NOT NULL;


-- 9. 어떤 계열
SELECT CATEGORY 
FROM TB_DEPARTMENT
GROUP BY CATEGORY
ORDER BY CATEGORY ASC;

-- 10. 
SELECT STUDENT_NO, STUDENT_NAME, STUDENT_SSN 
FROM TB_STUDENT
WHERE TO_CHAR(ENTRANCE_DATE,'YYYY') = '2002'
AND ABSENCE_YN != 'Y'
AND SUBSTR(STUDENT_ADDRESS, 1, 2) = '전주';







