SELECT * FROM TB_DEPARTMENT;
SELECT * FROM TB_CLASS;
SELECT * FROM TB_PROFESSOR;
SELECT * FROM TB_CLASS_PROFESSOR;
SELECT * FROM TB_STUDENT;
SELECT * FROM TB_GRADE;

-----------------------------------------------------------------
-- SELECT (OPTION)


-- 1. 영어영문 학번, 이름, 입학년도
SELECT STUDENT_NO 학번, STUDENT_NAME 이름, ENTRANCE_DATE 입학년도
FROM TB_STUDENT S
JOIN TB_DEPARTMENT D ON (S.DEPARTMENT_NO = D.DEPARTMENT_NO)
WHERE D.DEPARTMENT_NO = '002'
ORDER BY ENTRANCE_DATE ASC;


-- 2. 세글자가 아닌 교수님 이름, 주민번호
SELECT PROFESSOR_NAME, PROFESSOR_SSN 
FROM TB_PROFESSOR
WHERE LENGTH(PROFESSOR_NAME ) != 3;



-- 3. 교수님 이름, 나이
SELECT PROFESSOR_NAME 교수이름, 
ABS(FLOOR(MONTHS_BETWEEN(SYSDATE, TO_DATE(SUBSTR(PROFESSOR_SSN,1,6), 'RRMMDD')) / 12)) "나이"
FROM TB_PROFESSOR
WHERE DECODE(SUBSTR(PROFESSOR_SSN,8,1), '1', '남', '2', '여') = '남'
ORDER BY "나이" ;

-- 나이 구하기
SELECT ABS(FLOOR(MONTHS_BETWEEN(SYSDATE, TO_DATE(SUBSTR(PROFESSOR_SSN,1,6), 'RRMMDD')) / 12)) "나이"
FROM TB_PROFESSOR;



-- 4. 성을 제외한 이름만 출력 
SELECT SUBSTR(PROFESSOR_NAME,2) 이름
FROM TB_PROFESSOR;



-- 5. 재수생 입학자
SELECT STUDENT_NO, STUDENT_NAME 
FROM TB_STUDENT
WHERE ABS(FLOOR(MONTHS_BETWEEN(ENTRANCE_DATE , TO_DATE(SUBSTR(STUDENT_SSN,1,6), 'RRMMDD')) /12 )) >= 20;

 
SELECT ABS(FLOOR(MONTHS_BETWEEN(ENTRANCE_DATE , TO_DATE(SUBSTR(STUDENT_SSN,1,6), 'RRMMDD')) /12 ))"나이"
FROM TB_STUDENT;



-- 6. 2020년 크리스마스는 무슨 요일인가?

SELECT TO_CHAR(TO_DATE('2020-12-25', 'YYYY-MM-DD'), 'DAY') 요일
FROM DUAL;


-- 7. 





-- 8. 2000년 이전 학번을 받은 학생 학번, 이름
SELECT STUDENT_NO, STUDENT_NAME 
FROM TB_STUDENT
WHERE STUDENT_NO NOT LIKE 'A%';



-- 9. 학번이 A517178 한아름 학생의 총 평점
SELECT ROUND(AVG(POINT), 1) 평점
FROM TB_GRADE
WHERE STUDENT_NO = 'A517178';


-- 10. 학과별 학생 수를 구해 학과번호, 학생수(명) 구하기
SELECT DEPARTMENT_NO 학과번호, COUNT(*) "학생수(명)"
FROM TB_STUDENT
GROUP BY DEPARTMENT_NO
ORDER BY DEPARTMENT_NO;


-- 11. 지도 교수 배정받지 못한 학생의 수
SELECT COUNT(*)
FROM TB_STUDENT
WHERE COACH_PROFESSOR_NO IS NULL;


-- 12. A112113 김고운 학생의 년도 별 평점
SELECT SUBSTR(TERM_NO, 1, 4) 년도, ROUND(AVG(POINT), 1) "년도 별 평점"
FROM TB_GRADE
WHERE STUDENT_NO = 'A112113'
GROUP BY SUBSTR(TERM_NO, 1, 4)
ORDER BY 1;


-- 13. 학과 별 휴학생 수
SELECT DEPARTMENT_NO 학과코드명, 
SUM(DECODE(ABSENCE_YN, 'Y', 1, 0)) "휴학생 수"
FROM TB_STUDENT
GROUP BY DEPARTMENT_NO
ORDER BY 1;



-- 14. 동명이인 학생 수

SELECT STUDENT_NAME 동일이름, COUNT(*) "동명인 수"
FROM TB_STUDENT
GROUP BY STUDENT_NAME
HAVING COUNT(*) > 1
ORDER BY 1;


-- 15. A112113 김고운 학생의 년도 학기별 평점과 년도 별 누적 평점, 총 평점
SELECT SUBSTR(TERM_NO, 1, 4) 년도, NVL(SUBSTR(TERM_NO,5,2)) 학기, ROUND(AVG(POINT),1) 평점
FROM TB_GRADE
WHERE STUDENT_NO = 'A112113'
GROUP BY ROLLUP SUBSTR(TERM_NO, 1, 4), SUBSTR(TERM_NO,5,2))
ORDER BY SUBSTR(TERM_NO,1, 4);


-- 15번
-- 학번이 A112113인 김고운 학생의 년도, 학기 별 평점과 년도 별 누적 평점, 총 평점을 구하는 SQL문을 작성하시오.
-- (단, 평점은 소수점 1자리까지만 반올림하여 표시한다.)
SELECT NVL(SUBSTR(TERM_NO,1,4), ' ') AS 년도, NVL(SUBSTR(TERM_NO,5,2),' ') AS 학기, ROUND(AVG(POINT),1) AS 평점
FROM TB_GRADE
WHERE STUDENT_NO = 'A112113'
GROUP BY ROLLUP(SUBSTR(TERM_NO,1,4),SUBSTR(TERM_NO,5,2))
ORDER BY SUBSTR(TERM_NO,1,4);


SELECT * FROM TB_DEPARTMENT;
SELECT * FROM TB_STUDENT;
SELECT * FROM TB_GRADE;







